# run with command ""ruff -check""
# derogation : # noqa F401

[lint]

select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

# E501 = line-too-long
# B011 = assert-false
# PT015 = pytest-assert-always-false
# S101 = pytest-assert-always-false
ignore = ["E501", "B011", "PT015", "S101"]





