ENGLAND
F GOL c A NAF - TUS;(dislodged)
F IRI - ENG;(failed)
F LON s F YOR - NTH;(cut)
A NAF - TUS;(failed)
F TUN s F WES;(cut);(paradox)
F WES C A NAF - TUS
F YOR - NTH;(failed)

FRANCE
F BEL s F ENG;(cut);(paradox)
F ENG C A PIC - LON
F MAR - GOL
A PIC - LON;(failed)
F SPAsc S F MAR - GOL

GERMANY
F BAL C A SWE - LVN
F NTH C A NWY - BEL
A NWY - BEL;(failed)
A SWE - LVN;(failed)

ITALY
F ADR c A APU - TRI;(dislodged)
A APU - TRI;(failed)
A ROM - TUN;(failed)
F TUS S F TYN
F TYN C A ROM - TUN

AUSTRIA
F ALB - ADR
F TRI S F ALB - ADR

RUSSIA
F BLA C A RUM - ANK
F LVN s german F BAL;(cut);(paradox)
A RUM - ANK;(failed)

TURKEY
F ANK S F CON - BLA
F ARM S F BULec - BLA
F BULec - BLA;(failed)
F CON - BLA;(failed)
F ION S F NAP - TYN
F NAP - TYN;(failed)

