ENGLAND
A FIN - STP;(failed)
F SKA - SWE

FRANCE
F GAS - SPAnc;(failed)
F GOL S italian F TYN - WES
F MID S F SPAsc - WES
F SPAsc - WES;(failed)

GERMANY
A BER - PRU
F BOT S english A FIN - STP
A PRU - WAR
A SIL S A PRU - WAR

ITALY
A MAR S french F GAS - SPAnc
F TYN - WES;(failed)

AUSTRIA
F ION S turkish F TUN
A NAF S F WES - TUN
F WES - TUN;(failed)

RUSSIA
F BAR S english A FIN - STP
A LVN - STP;(failed)
A MOS S A LVN - STP
F STPsc - BOT;(failed)
A WAR h;(dislodged)

TURKEY
F TUN H

